import { StyleSheet } from 'react-native';
import { COLORS } from './constants';

export const createThemedStyles = (isDarkMode: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: isDarkMode ? COLORS.DARKER_GREY_2 : COLORS.WHITE,
  },
  text: {
    color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    fontSize: 16,
    marginBottom: 10,
    fontFamily: 'Roboto',
  },
  button: {
    backgroundColor: isDarkMode ? COLORS.PURPLE : COLORS.BLUE,
    padding: 12,
    borderRadius: 8,
    elevation: 3,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  buttonText: {
    color: COLORS.WHITE,
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  tabbar: {
    position: 'absolute',
    bottom: 25,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: isDarkMode ? COLORS.DARK_GREY : COLORS.WHITE,
    marginHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 30,
    borderCurve: 'continuous',
    shadowColor: isDarkMode ? COLORS.BLACK : COLORS.DARK_GREY,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 15,
    shadowOpacity: isDarkMode ? 0.5 : 0.1,
    elevation: 5,
  },
  card: {
    backgroundColor: isDarkMode ? COLORS.GREY : COLORS.WHITE,
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    shadowColor: isDarkMode ? COLORS.BLACK : COLORS.LIGHT_GREY,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  cardTitle: {
    color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  cardPR: {
    color: isDarkMode ? COLORS.PURPLE : COLORS.BLUE,
    fontSize: 18,
    fontWeight: 'bold',
  },
  totalCard: {
    backgroundColor: isDarkMode ? '#2C2C2C' : '#F0F0F0',
    borderRadius: 20,
    padding: 25,
    marginBottom: 25,
    shadowColor: isDarkMode ? '#000' : '#888',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  totalTitle: {
    color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  programSection: {
    marginBottom: 25,
  },
  programName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    marginBottom: 5,
  },
  programDetails: {
    fontSize: 16,
    color: isDarkMode ? COLORS.LIGHT_GREY : COLORS.DARK_GREY,
    lineHeight: 22,
  },
  noProgram: {
    color: isDarkMode ? '#888' : '#666',
    fontStyle: 'italic',
    fontSize: 16,
  },
  workoutCard: {
    backgroundColor: isDarkMode ? COLORS.DARK_GREY : COLORS.LIGHT_GREY,
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
  },
  workoutDate: {
    fontSize: 18,
    fontWeight: 'bold',
    color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    marginBottom: 8,
  },
  startWorkoutButton: {
    backgroundColor: isDarkMode ? '#4A90E2' : '#2E78C5',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 15,
  },
  startWorkoutButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  workoutText: {
    fontSize: 16,
    color: isDarkMode ? COLORS.LIGHT_GREY : COLORS.DARK_GREY,
    lineHeight: 22,
  },
  exerciseItem: {
    marginTop: 12,
    padding: 12,
    backgroundColor: isDarkMode ? '#2c3e50' : '#ecf0f1',
    borderRadius: 8,
  },
  exerciseName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: isDarkMode ? '#ecf0f1' : '#2c3e50',
    marginBottom: 6,
  },
  setDetails: {
    fontSize: 16,
    color: isDarkMode ? '#bdc3c7' : '#34495e',
    marginLeft: 12,
    lineHeight: 22,
  },
  buttonContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  todayButton: {
    backgroundColor: COLORS.PINK,
    paddingVertical: 14,
    paddingHorizontal: 25,
    borderRadius: 30,
    elevation: 5,
    shadowColor: COLORS.DARK_GREY,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  todayButtonText: {
    color: COLORS.WHITE,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  colorlist: {
    width: '100%',
    height: 110,
    borderRadius: 18,
    marginBottom: 15,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
  },
  selectedDateContainer: {
    marginTop: 25,
    padding: 12,
  },
  colorlistcontainer: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexGrow: 1,
    justifyContent: 'center',
  },
  mainContainer: {
    flex: 1,
    padding: 20,
    backgroundColor: isDarkMode ? COLORS.DARKER_GREY_2 : COLORS.WHITE,
  },
  header: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  headerText: {
    fontSize: 30,
    color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  rewardsCard: {
    marginBottom: 0,
    backgroundColor: isDarkMode ? COLORS.GREY : COLORS.LIGHT_GREY,
    borderRadius: 15,
    padding: 25,
    alignItems: 'center',
  },
  stakeAmount: {
    fontSize: 26,
    fontWeight: 'bold',
    color: COLORS.BLUE,
    marginBottom: 10,
  },
  rewardAmount: {
    fontSize: 26,
    fontWeight: 'bold',
    color: COLORS.GREEN,
    marginBottom: 10,
  },
  input: {
    marginTop: 0,
    width: '100%',
    height: 45,
    borderColor: isDarkMode ? COLORS.LIGHT_GREY : COLORS.GREY,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    marginBottom: 15,
    color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    backgroundColor: isDarkMode ? COLORS.DARK_GREY : COLORS.WHITE,
    fontSize: 16,
  },
  rewardsButton: {
    marginTop: 0,
    backgroundColor: COLORS.BLUE,
    padding: 12,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  unstakeButton: {
    marginTop: 12,
    backgroundColor: COLORS.RED,
    padding: 12,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  stakeImage: {
    width: 120,
    height: 120,
    marginTop: 0,
    marginBottom: 15,
  },
  dashboardSection: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  activityItem: {
    fontSize: 16,
    color: isDarkMode ? COLORS.LIGHT_GREY : COLORS.DARK_GREY,
    marginBottom: 8,
    lineHeight: 22,
  },
  workoutSection: {
    marginTop: 25,
  },
  messageContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 25,
  },
  messageText: {
    fontSize: 20,
    textAlign: 'center',
    color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    lineHeight: 28,
  },
  multiplierText: {
    fontSize: 18,
    color: isDarkMode ? COLORS.LIGHT_GREY : COLORS.DARK_GREY,
    marginTop: 8,
  },
  programListContainer: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    paddingBottom: 100,
    backgroundColor: isDarkMode ? COLORS.DARKER_GREY_2 : COLORS.WHITE,
  },
  program: {
    width: '100%',
    minHeight: 160,
    borderRadius: 30,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    position: 'relative',
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  selectedProgram: {
    borderWidth: 3,
    borderColor: COLORS.YELLOW,
  },
  programText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.WHITE,
    marginBottom: 12,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  exerciseText: {
    fontSize: 16,
    color: COLORS.WHITE,
    textAlign: 'center',
    lineHeight: 22,
  },
  checkMark: {
    fontSize: 24,
    color: COLORS.WHITE,
    position: 'absolute',
    top: 15,
    right: 15,
  },
  createButton: {
    backgroundColor: COLORS.GREEN,
    padding: 18,
    borderRadius: 30,
    alignItems: 'center',
    marginTop: 25,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  createButtonText: {
    color: COLORS.WHITE,
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  editOptions: {
    position: 'absolute',
    top: 15,
    right: 15,
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 20,
    padding: 8,
  },
  editButton: {
    marginRight: 12,
    padding: 6,
  },
  deleteButton: {
    padding: 6,
  },
});

export const getCalendarTheme = (isDarkMode: boolean) => ({
  backgroundColor: isDarkMode ? COLORS.DARKER_GREY_2 : COLORS.WHITE,
  calendarBackground: isDarkMode ? COLORS.DARKER_GREY_2 : COLORS.WHITE,
  textSectionTitleColor: isDarkMode ? COLORS.WHITE : COLORS.GREY,
  dayTextColor: isDarkMode ? COLORS.WHITE : COLORS.GREY,
  todayTextColor: COLORS.PINK,
  selectedDayBackgroundColor: COLORS.PINK,
  selectedDayTextColor: COLORS.WHITE,
  monthTextColor: isDarkMode ? COLORS.WHITE : COLORS.GREY,
  arrowColor: isDarkMode ? COLORS.WHITE : COLORS.GREY,
  dotColor: COLORS.PINK,
  selectedDotColor: COLORS.WHITE,
  disabledArrowColor: isDarkMode ? COLORS.DARK_GREY : COLORS.LIGHT_GREY,
  textDisabledColor: isDarkMode ? COLORS.DARK_GREY : COLORS.LIGHT_GREY,
  'stylesheet.calendar.header': {
    dayTextAtIndex0: {
      color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    },
    dayTextAtIndex6: {
      color: isDarkMode ? COLORS.WHITE : COLORS.GREY,
    },
  },
});